### ISSUE TITLE
Need to add junctions before mapping

### ISSUE THREAD

**Issue by sstein93** [Xinglab/rPGA#2]
In the manual it says to do the mapping and then add the junctions ($rPGA junctions add /path/to/known_splice_junctions) . But, if I  try to do the mapping before adding the gtf file I get the error:

Traceback (most recent call last):
  File "/u/home/s/sstein93/local/bin/rPGA", line 9, in <module>
    load_entry_point('rPGA==0.0.1', 'console_scripts', 'rPGA')()
  File "/u/home/s/sstein93/local/lib/python2.7/site-packages/rPGA/scripts/rPGA.py", line 47, in main
    running.main(sys.argv[2:])
  File "/u/home/s/sstein93/local/lib/python2.7/site-packages/rPGA/scripts/running.py", line 490, in main
    gtf = open(".rPGAJunctions.yaml").readline().rstrip()
IOError: [Errno 2] No such file or directory: '.rPGAJunctions.yaml'

**Comment by bahramis** [comment]
Good catch. In the original structure the user should have entered all the input at the beginning. I changed the structure once I started to put the figure together, forgot to fix the code. Anyways, it's fixed.
